//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyarskiyAirport.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int id { get; set; }
        public Nullable<int> idAircompany { get; set; }
        public int idPlane { get; set; }
        public int idAirPort { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public Nullable<System.DateTime> DateTimeArrival { get; set; }
        public Nullable<decimal> PriceEconom { get; set; }
        public Nullable<decimal> PriceBusiness { get; set; }
        public Nullable<System.DateTime> DateTimeStartGMT { get; set; }
        public Nullable<System.DateTime> DateTimeArrivalGMT { get; set; }
        public bool StatusIsFly { get; set; }
    
        public virtual Aircompany Aircompany { get; set; }
        public virtual AirPort AirPort { get; set; }
        public virtual Plane Plane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
