//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyarskiyAirport.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public int idFlight { get; set; }
        public int idPassenger { get; set; }
        public int idBuyer { get; set; }
        public string Class { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
