//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyarskiyAirport.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PlanesPassengers
    {
        public int id { get; set; }
        public string ModelPlane { get; set; }
        public Nullable<int> Passengers_Count { get; set; }
    }
}
